 #ifndef	__FIXDEF_DEFINE__
#define	__FIXDEF_DEFINE__

#define	   FID_BCZJYE			501		//本次资金余额
#define	   FID_BFXJJ			502		//买风险基金
#define	   FID_BGHF				503		//买过户费
#define	   FID_BJE				504		//买入金额
#define	   FID_BJSF				505		//买经手费
#define	   FID_BPGDH			506		//报盘股东号
#define	   FID_CODE				507		//返回码
#define	   FID_MESSAGE			508		//返回说明
#define	   FID_BSL				509		//买入数量
#define	   FID_BYHS				510		//买印花税
#define	   FID_BZ				511		//币种
#define	   FID_BZBM				512		//币种编码
#define	   FID_BZGF				513		//买证管费
#define	   FID_BZMC				514		//币种名称
#define	   FID_CBJS				515		//成本积数
#define	   FID_CBM				516		//字符编码
#define	   FID_CDID				517		//菜单ID号
#define	   FID_CDMC				518		//菜单名称
#define	   FID_CDTIME			519		//菜单可用时间
#define	   FID_CDTS				520		//菜单提示
#define	   FID_CDWZID			521		//菜单位置ID
#define	   FID_CJBH				522		//成交编号
#define	   FID_CJGY				523		//创建柜员
#define	   FID_CJJE				524		//成交金额
#define	   FID_CJJG				525		//成交价格
#define	   FID_CJRQ				526		//成交日期
#define	   FID_CJSJ				527		//成交时间
#define	   FID_CJSL				528		//成交数量
#define	   FID_CKLL				529		//存款利率
#define	   FID_CS				530		//城市
#define	   FID_CSZ				531		//参数值
#define	   FID_DH				532		//电话
#define	   FID_DJLB				533		//冻结类别
#define	   FID_DLRDH			534		//代理人电话
#define	   FID_DLRDZ			535		//代理人地址
#define	   FID_DLRMM			536		//代理人密码
#define	   FID_DLRQX			537		//代理人权限
#define	   FID_DLRSFZH			538		//代理人身份证号
#define	   FID_DLRXM			539		//代理人姓名
#define	   FID_DRMCCJJE			540		//当日卖出成交金额
#define	   FID_DRMCCJSL			541		//当日卖出成交数量
#define	   FID_DRMCJDZJ			542		//当日卖出解冻资金
#define	   FID_DRMCWTSL			543		//当日卖出委托数量
#define	   FID_DRMRCJJE			544		//当日买入成交金额
#define	   FID_DRMRCJSL			545		//当日买入成交数量
#define	   FID_DRMRDJZJ			546		//当日买入冻结资金
#define	   FID_DRMRWTSL			547		//当日买入委托数量
#define	   FID_DRQS				548		//当日已成交的清算资金
#define	   FID_DTB				549		//跌停板
#define	   FID_DZ				550		//地址
#define	   FID_DZLX				551		//待转利息
#define	   FID_EMAIL			552		//电子邮件
#define	   FID_EN_BZ			553		//可操作的币种
#define	   FID_EN_JYS			554		//可操作的交易所
#define	   FID_EN_KHH			555		//可操作的客户号
#define	   FID_EN_KHQZ			556		//允许操作的客户群组
#define	   FID_EN_YYB			557		//允许操作的营业部
#define	   FID_EN_ZQLB			558		//可操作的证券类别
#define	   FID_EX_KHH			559		//不可操作的客户号
#define	   FID_EX_KHQZ			560		//禁止操作的客户群组
#define	   FID_EX_YYB			561		//禁止操作的营业部
#define	   FID_EX_ZQLB			562		//不可操作的证券类别
#define	   FID_FATHERID			563		//父菜单

#define	   FID_FKEY				565		//加速键
#define	   FID_FLDM				566		//数据字典分类代码
#define	   FID_FLMC				567		//数据字典分类名称
#define	   FID_FLTSL			568		//非流通数量
#define	   FID_FSYYB			569		//发生营业部
#define	   FID_FWXM				570		//服务项目
#define	   FID_GDH				571		//股东号
#define	   FID_GDLB				572		//股东类别
#define	   FID_GDSFZH			573		//股东身份证号
#define	   FID_GDSX				574		//股东属性
#define	   FID_GDXM				575		//股东姓名
#define	   FID_GJDM				576		//国籍代码
#define	   FID_GMRQ				577		//柜员更密日期

#define	   FID_HKEY				579		//热键
#define	   FID_HKEYMASK			580		//组合键
#define	   FID_HTH				581		//合同号
#define	   FID_IBM				582		//数字编码
#define	   FID_JJR				583		//经纪人代码
#define	   FID_JJRLB			584		//经纪人类别
#define	   FID_JJRMM			585		//经纪人密码
#define	   FID_JJRQX			586		//经纪人权限
#define	   FID_JKP				587		//今开盘
#define	   FID_JSDM				588		//角色代码
#define	   FID_JSMC				589		//角色名称
#define	   FID_JSRQ				590		//结束日期
#define	   FID_JYDW				591		//交易单位
#define	   FID_JYFL				592		//交易分类
#define	   FID_JYFW				593		//交易范围
#define	   FID_JYJW				594		//交易价位
#define	   FID_JYLB				595		//交易类别编码
#define	   FID_JYLBMC			596		//交易类别名称
#define	   FID_JYLBXZ			597		//交易类别限制
#define	   FID_JYMM				598		//交易密码
#define	   FID_JYS				599		//交易所编码
#define	   FID_JYSDM			600		//交易所代码
#define	   FID_JYSJC			601		//交易所名称
#define	   FID_JYSQC			602		//交易所全称
#define	   FID_KCRQ				603		//开仓日期
#define	   FID_KEYMASK			604		//菜单组合键
#define	   FID_KHH				605		//客户号
#define	   FID_KHJB				606		//客户级别
#define	   FID_KHJL				607		//客户经理
#define	   FID_KHLB				608		//客户类别
#define	   FID_KHQC				609		//客户全称
#define	   FID_KHQZ				610		//客户群组
#define	   FID_KHRQ				611		//开户日期
#define	   FID_KHSX				612		//客户属性
#define	   FID_KHXM				613		//客户姓名
#define	   FID_KHZT				614		//客户状态
#define	   FID_KMCSL			615		//可卖出数量
#define	   FID_KMRSL			616		//可买入数量
#define	   FID_KQZJ				617		//可取资金
#define	   FID_KSRQ				618		//开始日期
#define	   FID_KYZJ				619		//可用资金
#define	   FID_LL				620		//利率
#define	   FID_LX				621		//预计利息
#define	   FID_LXJS				622		//利息积数
#define	   FID_LXS				623		//预计利息税
#define	   FID_LXSL				624		//利息税率
#define	   FID_MCJE				625		//卖出金额
#define	   FID_MCJJ				626		//卖出均价
#define	   FID_MCJS				627		//卖出基数
#define	   FID_MCSL				628		//卖出数量
#define	   FID_MENUID			629		//菜单的系统代码
#define	   FID_MKBH				630		//模块编号
#define	   FID_MM				631		//密码
#define	   FID_MMXZ				632		//买卖限制
#define	   FID_MMYK				633		//买卖盈亏
#define	   FID_MRJE				634		//买入金额

#define	   FID_MRJJ				636		//买入均价
#define	   FID_MRJS				637		//买入基数
#define	   FID_MRSL				638		//买入数量
#define	   FID_NBMC				639		//摘要内部名称
#define	   FID_NEWMM			640		//新密码
#define	   FID_NODE				641		//操作站点
#define	   FID_NOTE				642		//说明
#define	   FID_PYDM				643		//拼音代码
#define	   FID_PZBZ				644		//是否打印凭证
#define	   FID_PZH				645		//凭证号
#define	   FID_QSJE				646		//清算金额
#define	   FID_QSZJ				647		//清算资金
#define	   FID_QYBM				648		//区域编码
#define	   FID_QZFW				649		//取值范围
#define	   FID_QZMC				650		//群组名称
#define	   FID_RQ				651		//日期
#define	   FID_RZJE				652		//融资金额
#define	   FID_RZLL				653		//融资利率
#define	   FID_SFXJJ			654		//卖风险基金
#define	   FID_SGHF				655		//卖过户费
#define	   FID_SJCD				656		//数据长度
#define	   FID_SJE				657		//卖出金额
#define	   FID_SJJJR			658		//上级经纪人
#define	   FID_SJSF				659		//卖经手费
#define	   FID_SJYYB			660		//上级营业部
#define	   FID_SLXZ				661		//数量限制
#define	   FID_SM				662		//说明
#define	   FID_SRZJYE			663		//上日资金余额
#define	   FID_SSL				664		//卖出数量
#define	   FID_SXLB				665		//属性类别
#define	   FID_SYHS				666		//卖印花税
#define	   FID_SZGF				667		//卖证管费
#define	   FID_T0JS				668		//当日应交收资金
#define	   FID_T1JS				669		//T+1清算应交收资金
#define	   FID_T2JS				670		//T+2清算应交收资金
#define	   FID_TBCBJ			671		//摊薄成本价
#define	   FID_TBTS				672		//特别提示
#define	   FID_TJFL				673		//统计分类
#define	   FID_TZJS				674		//透支积数
#define	   FID_TZLL				675		//透支利率
#define	   FID_USERGROUP		676		//用户组别
#define	   FID_USERID			677		//柜员号
#define	   FID_USERNAME			678		//柜员名称
#define	   FID_VALUE			679		//属性值
#define	   FID_WTFS				680		//委托方式
#define	   FID_WTH				681		//委托号
#define	   FID_WTJG				682		//委托价格
#define	   FID_WTLB				683		//委托类别
#define	   FID_WTSL				684		//委托数量
#define	   FID_WTSSL			685		//未交收证券数量
#define	   FID_WTSX				686		//委托上限
#define	   FID_WTXX				687		//委托下限
#define	   FID_XHRQ				688		//销户日期
#define	   FID_XLDM				689		//学历代码
#define	   FID_XM				690		//姓名
#define	   FID_XWDM				691		//席位代码
#define	   FID_YHDM				692		//银行代码
#define	   FID_YHZH				693		//银行帐号
#define	   FID_YWKM				694		//业务科目
#define	   FID_YWLB				695		//业务类别
#define	   FID_YWMC				696		//业务名称
#define	   FID_YYB				697		//营业部
#define	   FID_YYBJC			698		//营业部简称
#define	   FID_YYBLB			699		//营业部分类
#define	   FID_YYBMC			700		//营业部名称
#define	   FID_YYDH				701		//预约单号
#define	   FID_YZBM				702		//邮政编码
#define	   FID_ZDBJ				703		//最低报价
#define	   FID_ZDJ				704		//最低价
#define	   FID_ZDXW				705		//指定席位
#define	   FID_ZGBJ				706		//最高报价
#define	   FID_ZGJ				707		//最高价
#define	   FID_ZHFL				708		//资金帐户分类
#define	   FID_ZHYE				709		//帐户余额
#define	   FID_ZHZT				710		//帐户状态
#define	   FID_ZJBH				711		//证件编号
#define	   FID_ZJCQDJ			712		//资金长期冻结
#define	   FID_ZJLB				713		//证件类别
#define	   FID_ZJMM				714		//资金密码
#define	   FID_ZJYE				715		//资金余额
#define	   FID_ZJZH				716		//资金帐号
#define	   FID_ZQDJSL			717		//证券冻结数量
#define	   FID_ZQDJYE			718		//证券冻结余额
#define	   FID_ZQDM				719		//证券代码
#define	   FID_ZQLB				720		//证券类别
#define	   FID_ZQLBMC			721		//证券类别名称
#define	   FID_ZQMC				722		//证券名称
#define	   FID_ZQQC				723		//证券全称
#define	   FID_ZQSL				724		//证券数量
#define	   FID_ZSBH				725		//证书编号
#define	   FID_ZSP				726		//昨收盘
#define	   FID_ZT				727		//状态
#define	   FID_ZTB				728		//涨停板
#define	   FID_ZXJ				729		//最新价
#define	   FID_ZY				730		//摘要
#define	   FID_ZYDM				731		//职业代码
#define	   FID_ZZFS				732		//转帐申请方式
#define	   FID_ZZJE				733		//支汇票金额
#define	   FID_ZZKZ				734		//转帐控制
#define	   FID_MMLB				735		//密码类别
#define	   FID_ZZFX				736		//转帐方向
#define	   FID_NEWQZ			737		//新群组编号
#define	   FID_EN_ZJZH			738		//可操作的资金帐号
#define	   FID_LOGICAL			739		//逻辑判断操作（是、否）
#define	   FID_EN_TZLX			740		//是否调整利息
#define	   FID_SQFS				741		//申请方式
#define	   FID_CKCS				742		//存款次数限制
#define	   FID_CKZE				743		//存款总额限制
#define	   FID_CKDBSX			744		//存款单笔限制
#define	   FID_QKCS				745		//取款次数限制
#define	   FID_QKZE				746		//取款总额限制
#define	   FID_QKDBSX			747		//取款单笔限制
#define	   FID_TBBBJ				748		//摊薄保本价
#define	   FID_TBFDYK			749		//摊薄浮动盈亏

#define	   FID_WTSJ				750		//委托时间
#define	   FID_SBSJ				751		//申报时间
#define	   FID_MMLBSM			752		//买卖类别说明
#define	   FID_SBJG				753		//申报结果
#define	   FID_SBJGSM			754		//申报结果说明
#define	   FID_CXBZ				755		//撤销标志

#define	   FID_JCCL				757		//今持仓量
#define	   FID_WJSSL			758		//未交收数量
#define	   FID_ZXSZ				760		//最新市值
#define	   FID_FDYK				761		//浮动盈亏
#define	   FID_ROWCOUNT			762		//最大结果集
#define	   FID_BROWINDEX		763		//起始历史记录索引值
#define	   FID_DJZJ				764		//冻结资金

#define	   FID_S1				766		//佣金
#define	   FID_S2				767		//印花税
#define	   FID_S3				768		//过户费
#define	   FID_S4				769		//附加费
#define	   FID_S5				770		//结算费
#define	   FID_S6				771		//交易规费
#define	   FID_YSJE				772		//应收金额
#define	   FID_HGLXSR			773		//回购利息收入
#define	   FID_HGLXFC			774		//回购利息付出
#define	   FID_BZS1				775		//标准佣金
#define	   FID_BCZQSL			776		//本次股份余额
#define	   FID_BRZQSL			777		//本日股份余额
#define	   FID_BRZJYE			778		//本日资金余额
#define	   FID_GYMM				779		//柜员密码

#define	   FID_KHK				780		//客户卡号
#define	   FID_JMLX				781		//加密类型
#define	   FID_SQLB				782		//申请类别
#define	   FID_ZPJE				784		//支票金额
#define	   FID_GPSZ				785		//股票市值
#define	   FID_WTQRBZ			786		//委托确认标志
#define	   FID_COUNT			788		//笔数

#define	   FID_GDHH				789		//股东号前缀
#define	   FID_GDHL				790		//股东号长度
#define	   FID_ZQDML			791		//证券代码长度
#define	   FID_ENDWTH			792		//结束委托号
#define	   FID_LOGINID			793		//登录ID
#define	   FID_ZHXM				794		//帐户姓名
#define	   FID_JSZH				795		//结算帐户
#define	   FID_FAX				796		//传真FAX
#define	   FID_LSH				797		//流水号
#define	   FID_SFZH				798		//身份证号
#define	   FID_TZLX				799		//透支利息

#define	   FID_SRFS				801		//输入方式
#define	   FID_XJZC				802		//现金资产
#define	   FID_SRYE				803		//上日余额
#define	   FID_ZHSX				804		//帐户属性
#define	   FID_WJSJE			805		//未交收金额
#define	   FID_CQBZ				806		//存取标志
#define	   FID_YZZZBZ			807		//银证转帐标志
#define	   FID_FSJE				808		//发生金额
#define	   FID_ZPBZ				809		//支票标志
#define	   FID_SCZJYE			810		//上次资金余额
#define	   FID_YWPCH			811		//业务批次号
#define	   FID_DJRQ				812		//登记日期
//#define	 FID_SECTION			813		//配置段
#define	   FID_ITEM				814		//配置项
#define	   FID_XGRQ				815		//修改日期
#define	   FID_CSJB				816		//参数级别
#define	   FID_SXMC				817		//属性名称
#define	   FID_PZH2				818		//凭证号2
#define	   FID_LPID				819		//礼品ID号
#define	   FID_LPBM				820		//礼品编码
#define	   FID_LPMC				821		//礼品名称
#define	   FID_LPJZ				822		//礼品价值
#define	   FID_ZSFS				823		//赠送方式
#define	   FID_ZCKZED			824		//资产控制额度
#define	   FID_ZJKZED			825		//资金控制额度
#define	   FID_DJJE				826		//冻结金额
#define	   FID_YCDJJE			827		//异常冻结金额
#define	   FID_QSDM				828		//券商代码
#define	   FID_QSMC				829		//券商名称
#define	   FID_JGSM				830		//结果说明
#define	   FID_CZZD				831		//操作站点
#define	   FID_JGBM				832		//机构编码
#define	   FID_JGMC				833		//机构名称
#define	   FID_JGJC				834		//机构简称
#define	   FID_CITY				835		//城市
#define	   FID_PROVINCE			836		//省份
#define	   FID_SJJG				837		//上级机构
#define	   FID_SJJGLB			838		//上级机构类别
#define	   FID_JGLB				839		//机构类别
#define	   FID_SLTSFS			840		//数量提示方式
#define	   FID_EN_JYLB			841		//允许的交易类别
#define	   FID_MRJG1			842		//买入价格一
#define	   FID_MRSL1			843		//买入数量一
#define	   FID_MRJG2			844		//买入价格二
#define	   FID_MRSL2			845		//买入数量二
#define	   FID_MRJG3			846		//买入价格三
#define	   FID_MRSL3			847		//买入数量三
#define	   FID_MRJG4			848		//买入价格四
#define	   FID_MRSL4			849		//买入数量四
#define	   FID_MCJG1			850		//卖出价格一
#define	   FID_MCSL1			851		//卖出数量一
#define	   FID_MCJG2			852		//卖出价格二
#define	   FID_MCSL2			853		//卖出数量二
#define	   FID_MCJG3			854		//卖出价格三
#define	   FID_MCSL3			855		//卖出数量三
#define	   FID_MCJG4			856		//卖出价格四
#define	   FID_MCSL4			857		//卖出数量四
#define	   FID_DYBL				858		//抵押比例
#define	   FID_JJRXM			859		//经纪人姓名
#define	   FID_TPBZ				860		//停牌标志
#define	   FID_JSLX				861		//结算类型
#define	   FID_HBXH				862		//回报序号
#define	   FID_GDZT				863		//股东状态
#define	   FID_WTGY				864		//委托柜员
#define	   FID_FSSJ				865		//发生时间
#define	   FID_WTZKXS			866		//委托折扣系数
#define	   FID_CXZKXS			867		//查询折扣系数
#define	   FID_QTZKXS			868		//前台折扣系数
#define	   FID_ZQSZ				869		//证券市值
#define	   FID_WTSF				870		//委托收费
#define	   FID_CDSF				871		//撤单收费
#define	   FID_ZCZH				872		//转存帐号
#define	   FID_ZCBL				873		//转存比例
#define	   FID_SFFS				874		//收费方式
#define	   FID_SFBZ				875		//收费标准
#define	   FID_JFFS				876		//计费方式
#define	   FID_JFQD				877		//计费起点
#define	   FID_JFDW				878		//计费单位
#define	   FID_CZSJ				879		//操作时间
#define	   FID_CLJG				880		//处理结果
#define	   FID_GYFL				881		//柜员分类
#define	   FID_GYZT				882		//柜员状态
#define	   FID_XQXZ				883		//星期限制
#define	   FID_ZCXZ				884		//注册限制
#define	   FID_SLSX				885		//数量上限
#define	   FID_CDSL				886		//撤单数量
#define	   FID_YJZKXS			887		//佣金折扣系数
#define	   FID_FJFZKXS			888		//附加费折扣系数
#define	   FID_BH				889		//编号
#define	   FID_YJTCBL			890		//佣金提成比例
#define	   FID_YJFHSL			891		//佣金返还税率
#define	   FID_GYH				892		//柜员号
#define	   FID_LPDM				893		//礼品代码
#define	   FID_ZC				894		//资产
#define	   FID_SRJE				895		//收入金额
#define	   FID_FCJE				896		//付出金额
#define	   FID_CZBZ				897		//冲帐标志
#define	   FID_KSSJ				898		//开始时间
#define	   FID_JSSJ				899		//结束时间
#define	   FID_GMZQ				900		//更密周期
#define	   FID_SXZ				901		//属性值
#define	   FID_YHSX				902		//银行属性
#define	   FID_YHYW				903		//银行业务
#define	   FID_ZQYW				904		//证券业务
#define	   FID_ZJMMXY			905		//资金密码效验
#define	   FID_JYMMXY			906		//交易买卖效验
#define	   FID_YHMMXY			907		//银行买卖效验
#define	   FID_YHMC				908		//银行名称
#define	   FID_HBLB				909		//货币类别
#define	   FID_YHMM				910		//银行密码
#define	   FID_ZZBS				911		//转帐标识
#define	   FID_SQH				912		//申请号
#define	   FID_YHLSH			913		//银行流水号
#define	   FID_ZQLSH			914		//证券流水号
#define	   FID_BCYE				915		//本次余额
#define	   FID_SHLB				916		//审核类别
#define	   FID_SHJG				917		//审核结果
#define	   FID_YEGXSJ			918		//余额更新时间
#define	   FID_QSMM				919		//券商密码
#define	   FID_MMMY				920		//密码密钥
#define	   FID_CSMY				921		//传输密钥
#define	   FID_FJXX				922		//附加信息
#define	   FID_YHCLJG			923		//银行处理结果
#define	   FID_SQWD				924		//申请网点
#define	   FID_XYBZ				925		//效验标志
#define	   FID_YSQH				926		//原申请号
#define	   FID_JYBS				927		//交易标识
#define	   FID_CLLB				928		//处理类别
#define	   FID_ZHLB				929		//帐户类别
#define	   FID_FQF				930		//发起方
#define	   FID_HZBS				931		//汇总笔数
#define	   FID_HZJE				932		//汇总金额
#define	   FID_LY				933		//来源
#define	   FID_WDH				934		//网点号
#define	   FID_QD1				935		//起点一
#define	   FID_QD2				936		//起点二
#define	   FID_QD3				937		//起点三
#define	   FID_QD4				938		//起点四
#define	   FID_QD5				939		//起点五
#define	   FID_BL1				940		//佣金一
#define	   FID_BL2				941		//佣金二
#define	   FID_BL3				942		//佣金三
#define	   FID_BL4				943		//佣金四
#define	   FID_BL5				944		//佣金五
#define	   FID_KHJCGX			945		//客户继承关系
#define	   FID_SYZH1			946		//收益帐号一
#define	   FID_SYZH2			947		//收益帐号二
#define	   FID_JSTS				948		//计算天数
#define	   FID_TJJYR			949		//统计交易日
#define	   FID_TJTS				950		//统计天数
#define	   FID_FPBL				951		//分配比例
#define	   FID_ZKFS				952		//折扣方式
#define	   FID_ZJED				953		//资金额度
#define	   FID_ZCED				954		//资产额度
#define	   FID_GLF				955		//管理费
#define	   FID_YJDX				956		//佣金底限
#define	   FID_FHBZ				957		//复核标志
#define	   FID_BDSL				958		//变动数量
#define	   FID_HZFS				959		//汇总方式
#define	   FID_LPSL				960		//礼品数量
#define	   FID_LXBJ				961		//利息报价
#define	   FID_KLX				962		//卡类型
#define	   FID_KMC				963		//卡名称
#define	   FID_BSC				964		//标识串
#define	   FID_BSCKSWZ			965		//标识串开始位置
#define	   FID_FJC				966		//附加串
#define	   FID_FJCKSWZ			967		//附加串开始位置
#define	   FID_KHKSWZ			968		//卡号开始位置
#define	   FID_KHCD				969		//卡号长度
#define	   FID_EN_YWKM			970		//允许业务科目
#define	   FID_ZRSZ				971		//昨日市值
#define	   FID_NEXTDATA			972		//继续取数标志
#define	   FID_SYL				973		//收益率
#define	   FID_FHS1				974		//已返还佣金
#define	   FID_GJBM1			975		//国籍编码一
#define	   FID_GJBM2			976		//国籍编码二
#define	   FID_GJBM3			977		//国籍编码三
#define	   FID_GJMC				978		//国籍名称
#define	   FID_EGJMC			979		//国籍英文名称
#define	   FID_CCCB				980		//持仓成本
#define	   FID_BDRQ				981		//变动日期
#define	   FID_MMXYLX			982		//密码效验类型
#define	   FID_XZSJ				983		//限制时间
#define	   FID_KHDXLX			984		//客户对象类型
#define	   FID_JYSXGX			985		//交易所相关性
#define	   FID_BZXGX			986		//币种相关性
#define	   FID_QZXGX			987		//群组相关性
#define	   FID_EXFLG			988		//查询扩展信息标志
#define	   FID_MAX_D			989		//最大值（浮点）
#define	   FID_MIN_D			990		//最小值（浮点）
#define	   FID_MAX_L			991		//最大值（整型）
#define	   FID_MIN_L			992		//最小值（整型）
#define	   FID_GYFJQX			993		//柜员附加权限
#define	   FID_ZHTZE			994		//帐户投资额
#define	   FID_QSJE_B			995		//回报买清算资金
#define	   FID_QSJE_S			996		//回报卖清算资金
#define	   FID_FDYK_TB			997		//摊薄浮动盈亏
#define	   FID_LLCSLB			998		//利率参数类别
#define	   FID_EX_JJR			999		//禁止经纪人
#define	   FID_FHFS				1000	//佣金返还方式

//## 报表类
#define	   FID_RPT_NAME			1001
#define	   FID_RPT_REQTYPE		1002	//请求类型 0:请求变量
#define	   FID_RPT_VAR			1003	//报表交互变量
#define	   FID_RPT_XML			1004	//XML数据(所有数据)
#define	   FID_RPT_XML_NAME		1005	//XML名字
#define	   FID_RPT_XMLFORMT		1006	//XML格式文件
#define	   FID_RPT_MEMNAME		1009	//报表数据名称
#define	   FID_RPT_PRO			1010	//是否主数据集.	1:主数据集（显示在ApexListCtrl上）。

#define	   FID_BZ_FH			1001	//佣金返还币种
#define	   FID_HBDHBL			1002	//货币兑换比例
#define	   FID_SYZH3			1003	//收益帐户3
#define	   FID_SYBL1			1004	//收益比例1
#define	   FID_SYBL2			1005	//收益比例2
#define	   FID_SYBL3			1006	//收益比例3
#define	   FID_FY				1007	//交易费用
#define	   FID_JYZT				1008	//交易状态
#define	   FID_RQ2				1009	//日期2
#define	   FID_PROVINCEID		1010	//省份ID
#define	   FID_CITYID			1012	//城市ID
#define	   FID_SECTIONID		1014	//辖区ID
#define	   FID_SECTION			1015	//辖区名称
#define	   FID_SFZQ				1016	//收费周期
#define	   FID_WBJGLB			1017	//外部机构类别
//#define	   FID_YWLB			1018	//业务类别
#define	   FID_EN_YWLB			1019	//业务类别范围
#define	   FID_BZDM				1020	//标准代码
#define	   FID_WBDM				1021	//外部代码
#define	   FID_CSDM				1022	//参数代码
#define	   FID_CSMC				1023	//参数名称
#define	   FID_QZSM				1024   //取值说明
#define	   FID_EN_FJBZ			1025	//允许的附加标志
#define		FID_GZJJBZ			1026	//国债净价标志
#define		FID_JSJG			1027	//结算价格
#define		FID_CWLX			1028	//错误类型
#define		FID_CWDM			1029	//错误类型
#define		FID_CWSM			1030	//错误类型
#define		FID_ZXZS			1031	//最新指数
#define		FID_TZEBZ			1032	//投资额标志
#define		FID_KBBZ			1033	//佣金捆绑标志
#define		FID_KHTZFL			1034	//客户投资分类(tXTDM.KHTZFL)

#define		FID_MFDLCS			1040	//免费登录次数
#define		FID_DLXZCS			1041	//限制登录次数
#define		FID_Z_SJSX			1042	//每日使用时间上限(总)
#define		FID_S_SJSX			1043	//每日使用时间上限(单)
#define		FID_MMCSCS			1044	//密码尝试次数
#define		FID_JDSJ			1045	//自动解冻时间
#define		FID_MFHQCS			1046	//免费查询行情次数
#define		FID_HQSFSX			1047	//行情收费上限
#define		FID_HKSFSX			1048	//划卡收费上限
#define		FID_SJSFSX			1049	//使用时间收费上限
#define		FID_ZSFSX			1050	//总收费上限


#define		FID_DBYJXX			1051	//单笔佣金下限
#define		FID_DBYJSX			1052	//单笔佣金上限
#define		FID_YJKBCL			1053	//佣金捆绑方式 tXTDM.YJKBCL
#define		FID_YJDJFS			1054	//佣金定价方式 tXTDM.YJDJFS
#define		FID_FHGY			1055	//复核柜员
#define		FID_TJZQLB			1056	//统计证券类别
#define		FID_EXWTFS			1057	//屏蔽委托方式
#define		FID_FDBH			1058	//分段编号

#define		FID_ZHDM			1060	//专户代码
#define		FID_TZDW			1061	//投资单位
#define		FID_TZXX			1062	//投资下限
#define		FID_SYZKXS			1063	//收益折扣系统
#define		FID_SYTZFS			1064	//收益投资方式
#define		FID_TZJESX			1065	//投资金额上限
#define		FID_ZJLCDS			1066	//资金留存底数
#define		FID_TZBDJE			1067	//投资额变更数
#define		FID_ZHKHH			1068	//专户客户号
#define		FID_ZHZJZH			1069	//专户资金账户
#define		FID_LCJZJE			1070	//理财集中金额
#define		FID_LCFHJE			1071	//理财返还金额
#define		FID_SYZTZBZ			1072	//理财收益再投资标志
#define		FID_SYZTZZQ			1073	//收益再投资周期
#define		FID_LCZSY			1074	//理财总收益
#define		FID_SYZCJE			1075	//理财收益转存金额
#define		FID_SYZTZE			1076	//收益再投资金额
#define		FID_XYBH			1077	//协议编号
#define		FID_LCTZJE			1078	//理财投资金额

#define			FID_SGDM						1079	//专户申购代码
#define			FID_CLBZ						1080	//处理标志
#define			FID_FPSY						1081	//分配收益
#define			FID_GBZQL						1082	//公布中签率
#define			FID_SGSL						1083	//申购数量
#define			FID_SGJG						1084	//申购价格
#define			FID_SSRQ						1085	//上市日期
#define			FID_HKRQ						1086	//还款日期
#define			FID_SSDM						1087	//上市代码
#define			FID_PHDM						1088	//配号代码
#define			FID_HKDM						1089	//还款代码
#define			FID_SGRQ						1090	//申购日期
#define			FID_JEBL						1091	//金额比率
#define		FID_LCJZQTJE			1092	//理财集中金额
#define			FID_HZGDH						1093	//合作股东号

#define			FID_SYDX						1094	//适用对象
#define			FID_JYLJSFS						1095	//交易量计算方式
#define			FID_JYLLJZQ						1096	//交易量累计周期
#define			FID_DJFS						1097	//定价方式
#define			FID_BBJ							1098	//保本价
#define			FID_HZLB						1099	//合作帐户类别

#define			FID_FSJE_LCBJ					1100	//本金发生金额
#define			FID_BCYE_LCBJ					1101	//本次本金余额
#define			FID_FSJE_SY						1102	//收益发生金额
#define			FID_BCYE_SY						1103	//待转收益余额
#define			FID_FSJE_BZJ					1104	//保证金发生额
#define			FID_BCYE_BZJ					1105	//保证金帐户余额

#define	   FID_KHS				1110	//开户户数
#define	   FID_XHS				1111	//销户户数
#define	   FID_ZHS				1112	//总户数
#define	   FID_ZDGDHS			1113	//指定股东户数
#define	   FID_CXZDHS			1114	//撤销股东户数
#define	   FID_CCGDHS			1115	//持仓股东户数
#define	   FID_TJZJYE			1116	//统计资金余额
#define	   FID_TJZJCK			1117	//统计增加存款
#define	   FID_TJZJQK			1118	//统计增加取款
#define	   FID_TJZJGP			1119	//统计增加市值
#define	   FID_TJJSGP			1120	//统计减少市值
#define	   FID_TJGPSZ			1121	//统计股票市值
#define	   FID_TJZZC			1122	//统计总资产
#define	   FID_FDB1				1123	//统计分段开始1
#define	   FID_FDE1				1124	//统计分段结束1
#define	   FID_FDB2				1125	//统计分段开始2
#define	   FID_FDE2				1126	//统计分段结束2
#define	   FID_FDB3				1127	//统计分段开始3
#define	   FID_FDE3				1128	//统计分段结束3
#define	   FID_FDB4				1129	//统计分段开始4
#define	   FID_FDE4				1130	//统计分段结束4
#define	   FID_FDB5				1131	//统计分段开始5
#define	   FID_FDE5				1132	//统计分段结束5
#define	   FID_FDB6				1133	//统计分段开始6
#define	   FID_FDE6				1134	//统计分段结束6
#define		FID_TJJGGS			1135	//统计结果个数
#define		FID_TJJGSJ			1136	//统计结果数据
#define		FID_QSBZ			1137	//实时清算标志
#define		FID_TZJE			1138	//透支金额
#define		FID_WJSZJ			1139	//未交收资金

#define		FID_YDZD			1141	//应答字段
#define		FID_YDZDSM			1142	//应答字段说明
#define		FID_YDSJ			1143	//应答数据
#define		FID_JCJJE			1144	//净成交金额
#define		FID_YXHS			1145	//有效户数
#define		FID_CJSLBL			1146	//成交数量比例
#define		FID_CJJEBL			1147	//成交金额比例
#define		FID_S1BL			1148	//佣金收入比例
#define		FID_ZZCBL1			1149	//营业部的资产比例
#define		FID_ZZCBL2			1150	//总公司的资产比例
#define		FID_ZSLBL1			1151	//营业部的数量比例
#define		FID_ZSLBL2			1152	//总公司的数量比例
#define		FID_ZHSBL1			1153	//营业部的户数比例
#define		FID_ZHSBL2			1154	//总公司的户数比例
#define		FID_JEXX			1155	//金额下限

#define		FID_GSKH			1156	//银证转帐及银证通参数中的公司卡号信息
#define		FID_SBZT			1157	//银证转帐参数的申报状态
#define		FID_QDBZ			1158	//银证转帐参数的签到标志
#define		FID_WBZH			1159	//外部帐号
#define		FID_WBJGDM			1160	//外部机构代码
#define		FID_WBKYYE			1161	//外部帐户参考可用余额
#define		FID_WBLJZJ			1162	//外部帐户参考可取资金余额
#define		FID_WBDJJE			1163	//外部帐户参考冻结金额
#define		FID_JYXZ			1164	//银证通交易限制
#define		FID_ZJXYFS			1165	//银证通资金校验方式
#define		FID_HBBZ			1166	//银证通资料回报类型
#define		FID_ZJHZFS			1167	//银证通资金回转方式
#define		FID_BDDJJE			1168	//银证通客户买入委托时本地资金冻结数
#define		FID_ZZJSSJ			1170	//银证转帐停止正常转帐交易的时间

#define		FID_ZSZBL1			1180	//营业部的市值比例
#define		FID_ZSZBL2			1181	//总公司的市值比例

#define		FID_XCMRJ			1186	//现钞买入价
#define		FID_XCMCJ			1187	//现钞卖出价
#define		FID_XHMRJ			1188	//现汇买入价
#define		FID_XHMCJ			1189	//现汇卖出价
#define		FID_GSBL			1190	//估算比例
#define		FID_HLBZ			1191	//汇率标志

#define		FID_DRCKJE			1192	//当日帐户存款金额
#define		FID_TZCKJE			1193	//当日通知存款金额

#define		FID_JGMC_E			1194	//机构英文名称
#define		FID_FRDB			1195	//法人代表
#define		FID_FRSFZH			1196	//法人身份证号
#define		FID_HYLB			1197	//行业类别
#define		FID_YWFW			1198	//业务范围
#define		FID_ZCDZ			1199	//注册地址
#define		FID_ZCZB			1200	//注册资本

#define	   FID_SQL				1201
#define	   FID_MEMHEAD			1202
#define	   FID_MEMDATA			1203
#define	   FID_MEMCOUNT			1204
#define	   FID_MEMSIZE			1205

#define		FID_FILENAME		1201	//文件名称
#define		FID_FILEVERSION		1202	//文件版本

#define		FID_ZCYE			1201	//资产余额
#define		FID_FZYE			1202	//负债余额
#define		FID_YSZC			1203	//原始资产

#define		FID_YWXZ			1205	//业务限制
#define		FID_SJXM			1206	//审计项目
#define		FID_SJMC			1207	//审计名称
#define		FID_JS				1208	//债券增值积数


#define		FID_CCJJ			1209	//持仓均价
#define		FID_LJYK			1210	//累计盈亏
#define		FID_PGSL			1211	//配股数量



#define		FID_BL			1212   //比例
#define		FID_CSLB		1213		//参数类别
#define		FID_FJBZ		1214		//附加标识
#define		FID_QZQKBZ		1215		//强制取款标志
#define		FID_SORTTYPE	1216	//数据查询的排序方式 0,正常顺序(先后) 1,逆序(后先)
#define		FID_ZCXX		1217	//资产下限
#define		FID_ZCSX		1218	//资产上限
#define		FID_TIME			1219	//操作时间
#define		FID_PGJE			1220	//配股金额

				//以下为债券系统特别需要

#define		FID_TGZH		1221	//债券系统托管帐户
#define		FID_GZQX		1222	//国债期限
#define		FID_HGTS		1223	//回购天数
#define		FID_GZJYSX		1224	//国债交易属性
#define		FID_ZRKHH		1225	//转入客户号
#define		FID_GZNBDM		1226	//债券内部代码
#define		FID_GZFJSX		1227	//国债附加属性
#define		FID_GZMZSX		1228	//面值属性
#define		FID_GZJXTS		1229	//国债计息天数
#define		FID_FXJG		1230	//债券发行价格
#define		FID_TGBH		1231	//托管编号
#define		FID_DYSL		1232	//抵押数量
#define		FID_TGRQ		1233	//托管日期
#define		FID_SXF			1234	//手续费
#define		FID_DJSL		1235	//冻结数量
#define		FID_CQDJ		1236	//长期冻结
#define		FID_JYFY		1237	//交易费用
#define		FID_DQBX		1238	//债券到期本息
#define		FID_GZLL		1239	//国债利率
#define		FID_DQRQ		1240	//到期（兑付日期）
#define		FID_JSJXRQ		1241	//开始记息日期
#define		FID_LTRQ		1242	//开始流通日期
#define		FID_FXZQDJR		1243	//派息登记日
#define		FID_ZQFXRQ		1244	//派息日
#define		FID_DFZQDJR		1245	//兑付登记日
#define		FID_BRLX		1246	//记账式债券单位（100）本日利息
#define		FID_HGJG		1247	//回购价格
#define		FID_GHJG		1248	//购回价格
#define		FID_KTBZ		1249	//开通标志
#define		FID_HGSL		1250	//回购数量
#define		FID_HGRQ		1251	//回购日期
#define		FID_GHRQ		1252	//购回日期
#define		FID_ZRTGZH		1253	//转入托管帐户
#define		FID_QTZC		1254	//其他资产
#define		FID_ZZC			1255	//总资产
#define		FID_WQSZJ		1256	//未清算资金
#define		FID_JGDM		1257	//机构代码
#define		FID_DFSXFL		1258	//兑付手续费率
#define		FID_DFLXSL		1259	//兑付利息税率
#define		FID_JXFS		1260	//计息方式

#define		FID_YXHSBL1		1300			//营业部有效户数比例
#define		FID_YXHSBL2		1301			//总部有效户数比例
#define		FID_ENDKHH		1302			//结束客户号

#define		FID_FILETRANSIZE	1304	//文件传送时的大小,比如：压缩后
#define		FID_FILESIZE		1303	//文件大小

//Add Jerry	Gu	2003.4.21
#define			FID_YJL					1303					//佣金率
#define			FID_YJLXX				1304				   //最低佣金率
#define			FID_YJXX				1305	 //最低佣金
#define			FID_YJSX				1306	 //最高佣金
#define			FID_YHSL				1307	 //印花税率
#define			FID_GHFL				1308	 //过户费率
#define			FID_GHFXX				1309	 //最低过户费
#define			FID_GHFSX				1310	 //最高过户费
#define			FID_FJF					1311	 //附加费
#define			FID_JSFL				1312	 //结算费率
#define			FID_JSFXX				1313	 //最低结算费
#define			FID_JSFSX				1314	 //最高结算费
#define			FID_JYGFL				1315	 //交易规费率
#define			FID_JYGFXX				1316	 //交易规费下限
#define			FID_JYGFSX				1317	 //交易规费上限
#define			FID_QTFL				1318	 //其它费率
#define			FID_QTFXX				1319	 //最低其他费用
#define			FID_QTFSX				1320	 //最高其他费用
#define			FID_FID					1321	//字段FID

//add by DaiXiaoGe 2003.05.09 客户服务定制
#define			FID_FWDM				1323		//客户服务代码
#define			FID_FWMC				1324		//客户服务名称
#define			FID_FWLX				1325		//客户服务类型
#define			FID_SLZT				1326		//客户服务受理主体
#define			FID_CLFS				1327		//客户服务处理方式
#define			FID_FILE				1328		//文件名
#define			FID_FILE2				1329		//文件名二
#define			FID_PROCNAME			1330		//过程名
#define			FID_CSXH				1331		//参数序号
#define			FID_TYPE				1332		//参数类型
#define			FID_QSZ					1333		//缺省值
#define			FID_CS1					1335		//参数1
#define			FID_CS2					1336		//参数2
#define			FID_CS3					1337		//参数3
#define			FID_CS4					1338		//参数4
#define			FID_CS5					1339		//参数5
#define			FID_CS6					1340		//参数6
#define			FID_CS7					1341		//参数7
#define			FID_CS8					1342		//参数8
#define			FID_CS9					1343		//参数9
#define			FID_CS10				1344		//参数10
#define			FID_CS11				1345		//参数11
#define			FID_CS12				1346		//参数12
#define			FID_CS13				1347		//参数13
#define			FID_CS14				1348		//参数14
#define			FID_CS15				1349		//参数15
#define			FID_OPTERATOR				1350		//核心开户操作类型
#define			FID_OPTION				1351		//核心开户参数1
#define			FID_PACKINDEX				1352		//数据包序列号
#define			FID_GYDM                           	1353            //柜员代码
#define			FID_JYJS				1354		//交易基数
#define			FID_QTSX				1355		//其他属性
#define			FID_TDJY				1356		//替代交易

#define			FID_MRJG5				1357	//买入价格5
#define			FID_MRSL5				1358	//买入数量5
#define			FID_MCJG5				1359	//卖出价格5
#define			FID_MCSL5				1360	//卖出数量5

#define		FID_FILEWRITETIME	1404	//文件修改时间
#define		FID_FILEDATA		1505	//文件数据
#define		FID_FILEZIP			1506	//文件是否压缩传送(由服务端决定)
#define		FID_FILECOMPANYNAME	1507	//文件的公司名称
#define		FID_FILEPRODUCTNAME	1508	//文件的相关产品名称
#define		FID_FILEDIR			1509	//文件所存放目录
#define		FID_FILENEW			1510	//是新文件，强制用户更新
#define		FID_FILERELATION	1511	//上传数据块与已存在的文件的关系(0 新建,1 追加,2 文件指定位置覆盖)
#define		FID_FILEPOSITION	1512	//文件中相对于文件头的偏移
#define		FID_FILETYPE		1513	//文件的业务类型


// 开放基金	2000-----2499
#define		FID_OFSS_TADM				2000	//TA代码	 
#define		FID_OFSS_JSLX				2001	//结算类型
#define		FID_OFSS_JSJG				2002	//结算机构
#define		FID_OFSS_JSZH				2003	//结算帐号
#define		FID_OFSS_BZ					2004	//结算币种
#define		FID_OFSS_JYFW				2005	//交易范围
#define		FID_OFSS_YJFS				2007	//邮寄方式	
#define		FID_OFSS_FHFS				2008	//分红方式
#define		FID_OFSS_JJZHSX				2009	//帐户属性
#define		FID_OFSS_JJZHLB		 		2010	//帐户类别
#define		FID_OFSS_JJZHZT		 		2011	//帐户状态
#define		FID_OFSS_JJZHXM			 	2012	//帐户姓名

#define		FID_OFSS_JJZH		 		2015	//基金帐号	
#define		FID_OFSS_KHZT		 		2016	//客户状态
#define		FID_OFSS_DJYY				2017	//冻结原因***
#define		FID_OFSS_JDYY				2019	//解冻原因***
#define		FID_OFSS_CRFE				2021	//存入份额***
#define		FID_OFSS_QCFE				2022	//取出份额***
#define		FID_OFSS_WTFE		 		2023	//委托份额
 
#define		FID_OFSS_WTFS			 	2025	//委托方式
#define		FID_OFSS_SQBH				2026	//申请编号	
#define		FID_OFSS_JJDM				2027	//基金代码	
#define		FID_OFSS_WTJE		 		2028	//委托金额
#define		FID_OFSS_JESHCL		 		2029	//巨额赎回处理标志
#define		FID_OFSS_YYRQ			 	2030	//预约日期		
#define		FID_OFSS_YSQBH				2031	//原申请编号	 
#define		FID_OFSS_DFXSDM			 	2032	//对方销售商代码	
#define		FID_OFSS_DFWDH		 		2033	//对方网点号
#define		FID_OFSS_DFJYZH		 		2034	//对方交易账号
#define		FID_OFSS_DFJJZH		 		2035	//对方基金帐号
#define		FID_OFSS_DFJJDM		 		2036	//对方基金代码
#define		FID_OFSS_DQSGRQ1			2037	//每月扣款日期1
#define		FID_OFSS_DQSGRQ2		 	2038	//每月扣款日期2
#define		FID_OFSS_DQSGRQ3		 	2039	//每月扣款日期3
#define		FID_OFSS_ZHSBFS		 		2042	//帐号识别方式
#define		FID_OFSS_FRDB		 		2043	//法人代表
 
//#define		FID_OFSS_YYB			 	2045	//营业部
#define		FID_OFSS_JJMC		 		2046	//基金名称
#define		FID_OFSS_ZQSL			 	2047	//基金数量	
#define		FID_OFSS_DJSL			 	2048	//冻结数量		 
#define		FID_OFSS_KYSL		 		2049	//可用数量
#define		FID_OFSS_YWDM			 	2051	//业务代码	 
#define		FID_OFSS_YWMC		 		2052	//业务名称
#define		FID_OFSS_QRFE		 		2054	//确认份额
#define		FID_OFSS_QRJE		 		2055	//确认金额
#define		FID_OFSS_SBJG		 		2057	//申报结果
#define		FID_OFSS_CDSJ				2058	//撤单时间		 
#define		FID_OFSS_JJZHZJLB			2064	//投资人证件类别
#define		FID_OFSS_JBRXM				2065	//经办人姓名		
#define		FID_OFSS_JBRZJLB			2066	//经办人证件类别	
#define		FID_OFSS_JBRZJBH			2067	//经办人证件编号	
#define		FID_OFSS_FRXM				2068	//法人姓名		
#define		FID_OFSS_FRZJLB				2069	//法人证件类别	
#define		FID_OFSS_FRZJBH				2070	//法人证件编号	
#define		FID_OFSS_YWLB				2071	//业务类别
#define		FID_OFSS_JYBM				2072 	//交易编码
#define		FID_OFSS_JGDM				2073	//机构代码
#define		FID_OFSS_JGMC				2074	//机构名称
#define		FID_OFSS_JGQC				2075	//机构全称
#define		FID_OFSS_TAMC				2076	//TA名称
#define		FID_OFSS_TYBM				2077	//统一编码
#define		FID_OFSS_TAJC				2078	//TA简称
#define		FID_OFSS_DZ					2079	//地址
#define		FID_OFSS_XGRQ				2080	//修改日期
#define		FID_OFSS_JJJC				2081	//基金简称
#define		FID_OFSS_JYZT				2082	//交易状态
#define		FID_OFSS_JJJZ				2083	//基金状态
#define		FID_OFSS_FXJG				2084	//发行价格
#define		FID_OFSS_FSXZ				2085	//
#define		FID_OFSS_PXFS				2086	//
#define		FID_OFSS_FXZFE				2087	//发行总份额
#define		FID_OFSS_GRZGBL				2088	//个人最高比例
#define		FID_OFSS_GRZGRGFE			2089	//个人最高认购份额
#define		FID_OFSS_GRZGRGZJ			2090	//个人最高认购金额
#define		FID_OFSS_FRZGRGFE			2091	//法人最高认购份额
#define		FID_OFSS_FRZGRGZJ			2092	//法人最高认购金额
#define		FID_OFSS_GRSCSGZDZJ			2093	//个人首次申购最低资金
#define		FID_OFSS_FRSCSGZDZJ			2094	//法人首次申购最低资金
#define		FID_OFSS_GRZJSGZDZJ			2095	//个人追加申购最低资金
#define		FID_OFSS_FRZJSGZDZJ			2096	//法人追加申购最低资金
#define		FID_OFSS_JJZSSHFE			2097	//基金最少赎回份额
#define		FID_OFSS_RGKSRQ				2098	//认购开始日期
#define		FID_OFSS_RGJSRQ				2099	//认购结束日期
#define		FID_OFSS_JSBZ				2100	//结算币种
#define		FID_OFSS_XXGGRQ				2101	//信息公告日期

#define		FID_OFSS_SCJYRQ				2103	//上次交易日期
#define		FID_OFSS_JJZHDJRQ			2104	//基金帐户冻结日期
#define		FID_OFSS_JJSL				2105	//基金份额数量
#define		FID_OFSS_ZXSZ				2106	//基金最新市值
#define		FID_OFSS_XSWD				2110	//销售网点
#define		FID_OFSS_JJZHSFZH			2111	//身份证号

#define		FID_OFSS_SQJE				2112	//申请金额
#define		FID_OFSS_DJZJ				2114	//冻结资金
#define		FID_OFSS_QSZJ				2115	//清算资金
#define		FID_OFSS_GSQX				2116	//挂失期限***
#define		FID_OFSS_DJQX				2117	//冻结期限***
#define		FID_OFSS_KKRQ				2118	//扣款日期
#define		FID_OFSS_YYBZ				2119	//预约标志
#define		FID_OFSS_BCDJSL				2120	//本次冻结数量
#define		FID_OFSS_DJJSRQ				2129	//冻结结束日期
#define		FID_OFSS_CZZD				2131	//操作站点
#define		FID_OFSS_JDJE				2132	//解冻金额
#define		FID_OFSS_BCDJ				2133	//本次冻结
#define		FID_OFSS_FCJE				2135	//付出金额
#define		FID_OFSS_SRJE				2136	//收入金额
#define		FID_OFSS_ZJYE				2137	//资金余额
#define		FID_OFSS_SQBHCD				2139	//申请编号长度
#define		FID_OFSS_JJZHCD				2140	//基金帐号长度
#define		FID_OFSS_GRJJZSSHFE			2141	//个人基金最少赎回份额
#define		FID_OFSS_GRJJZSZHFE			2142	//个人基金最少转换份额
#define		FID_OFSS_FRJJZSSHFE			2143	//法人基金最少赎回份额
#define		FID_OFSS_FRJJZSZHFE			2144	//法人基金最少转换份额
#define		FID_OFSS_DJFS				2145	//登记方式
#define		FID_OFSS_GHYY				2146	//过户原因
#define		FID_OFSS_JGZGBL				2147	//机构最高比例
#define		FID_OFSS_JJZSZHFE			2148	//基金最少转换份额
#define		FID_OFSS_PZDM				2149	//品种代码
#define		FID_OFSS_DQSGNS				2150	//年数
#define		FID_OFSS_LSDJ				2151	//临时冻结处理
#define		FID_OFSS_MCWTSL				2152	//卖出委托数量

#define		FID_OFSS_TALSH 				2153	//TA流水号 
#define		FID_OFSS_FELB  				2154	//份额类别 
#define		FID_OFSS_FHJJFE				2155	//分红基金份额 
#define		FID_OFSS_FHDWJE				2156	//分红单位金额 
#define		FID_OFSS_FHBZ  				2157	//分红标志 
#define		FID_OFSS_HLZJE 				2158	//红利总金额 
#define		FID_OFSS_SFZJE 				2159	//实发红利金额 
#define		FID_OFSS_HGZFE 				2160	//红股总份额 
#define		FID_OFSS_DJHGFE				2161	//冻结红股份额 
#define		FID_OFSS_QYDJRQ				2162	//权益登记日期 
#define		FID_OFSS_FHRQ  				2163	//分红日期 


//股票质押 LISH 2500 －－2550
#define	        FID_ZY_HTBH                             2501   //合同编号
#define	        FID_ZY_CZRBM                            2502   //出质人编码
#define	        FID_ZY_CZRMC                            2503   //出质人名称
#define	        FID_ZY_ZQRBM                            2504   //质权人编码
#define	        FID_ZY_ZQRMC                            2505   //质权人名称
#define	        FID_ZY_ZYHYBH                           2506   //质押合约编号
#define	        FID_ZY_DKHYBH                           2507   //贷款合约编号
#define	        FID_ZY_DKJE                             2508   //贷款金额
#define	        FID_ZY_DKDQRQ                           2509   //贷款到期日
#define	        FID_ZY_HTDJRQ                           2510   //合同登记日期
#define	        FID_ZY_GYDM                             2511   //合同编号
#define	        FID_ZY_KSRQ                             2512   //贷款到期日
#define	        FID_ZY_JSRQ                             2513   //合同登记日期
#define	        FID_ZY_WTZT                             2514   //委托状态
#define         FID_ZY_SHGY                             2515   //申核柜员
#define         FID_ZY_SHRQ                             2516   //申核日期
#define         FID_ZY_SHSJ                             2517   //申核时间
#define         FID_ZY_SHZD                             2518   //申核站点
//--end
#define         FID_KSKH                                2519   //开始客户号
#define         FID_JSKH                                2520   //结束客户号
#define         FID_BCZQYE                              2521   //本次证券余额
#define         FID_ZY_ZYZH                             2522   //质押帐号
#define         FID_ZY_DJBH                             2523   //质押帐号

//实时开户类自定义FID
#define		FID_CZLX		7000	//操作类型
#define		FID_ZQZH		7001	//证券账号
#define		FID_TXDZ		7003	//通信地址
#define		FID_LXDH		7004	//联系电话
#define		FID_CZH			7005	//传真号
#define		FID_YYBDM		7006	//营业部代码
#define		FID_CZYBH		7007	//操作员编号
#define		FID_KHDDH		7008	//开户点代号
#define		FID_QYLB		7009	//股东性质
#define		FID_TZRXM		7010	//投资人名称
#define		FID_TZRLB		7011	//投资人类别
#define		FID_ZJDM		7012	//证件代码
//#define	  FID_YSFZH		  7013	  //原股东姓名/单位全称
#define		FID_YSFZ	   7013	   //原股东姓名/单位全称
#define		FID_YGDXM		7014	//原身份证号/注册号码
#define		FID_XZQZH		7015	//最终证券帐号
#define		FID_QQLB		7016	//请求类别
#define		FID_YSFZH		7017	//原股东姓名/单位全称
//三板认领
#define	   FID_GDDM				7101	//老股东号
#define	   FID_SBGDDM			7102	//三板股东号
#define	   FID_GFXZ				7103	//股份性质
#define	   FID_DJGS				7104	//待登记，确认股数
#define	   FID_DHHM				7105	//电话号码
#define	   FID_WTXH				7106	//委托序号
#define	   FID_WTRQ				7107	//委托日期
#define	   FID_DYBZ				7108	//打印标志
#define	   FID_BZXX				7109	//备注信息
#define	   FID_TZRMC			7110	//股东姓名/单位全称
#define	   FID_ZJDM_OLD			7111	//原身份证号
#define	   FID_TZRMC_OLD		7112	//原股东姓名/单位全称
#define	   FID_SBBZ				7113	//申报标志
#define	   FID_CLSM				7114	//处理说明
#define	   FID_CXLB				7115	//查询类别
#define	   FID_XWH				7116	//席位号
#define	   FID_KHHY				7117	//开户会员
#define	   FID_TZRJC			7119	//投资人简称
#define	   FID_XB				7120	//性别
#define	   FID_TZLLB			7121	//投资人类别
#define	   FID_CSRQ				7122	//出生日期
#define	   FID_FRLB				7124	//法人类别
#define	   FID_HYDM				7125	//行业代码
#define	   FID_JSHY				7126	//结算会员
#define	   FID_GCZH				7127	//过出证券帐户
#define	   FID_GCXW				7128	//过出席位号
#define	   FID_GRZH				7129	//过入证券帐户
#define	   FID_GRXW				7130	//过入席位号
#define	   FID_HBRQ				7131	//回报日期
#define	   FID_YWLX				7132	//业务类型
#define	   FID_WWMC				7133	//外文名称
#define	   FID_TJSL				 7134	//统计数量
#define	   FID_SFJE				 7135	//收费金额
#define	   FID_DJGSSF			   7136	//登记公司收费
#define	   FID_DLJGSF			   7137	//代理机构收费
#define	   FID_GRSFZH			   7138	//待过入身份证号
#define	   FID_GRGDXM			   7139	//待过入股东姓名
#define	   FID_GRTXDZ			   7140	//待过入通讯地址
#define	   FID_GRDHHM			   7141	//待过入电话号码
#define	   FID_GRYZBM			   7142	//待过入邮政编码
#define	   FID_WTGS				 7143	//委托股数
#define	   FID_DFXW				 7144	//对方席位
#define	   FID_DFDM				 7145	//对方帐户
#define	   FID_DFXZ				 7146	//对方性质
#define	   FID_QRBZ				 7147	//确认标志


//## 文件下载类
#define		FUNC_ID_FILEINFO	1901	//文件检查
#define		FUNC_ID_GETFILE		1902	//文件下载
#define		FUNC_ID_ALLFILEINFO	1903	//全部文件信息
#define		FUNC_ID_UPLOADFILE	1904	//上传文件

//客户管理类

#define	   FUNC_KH_KHMMXG		11010	//客户密码修改
#define	   FUNC_KH_FWXMDJ				11035	//服务项目登记
#define	   FUNC_KH_FWXMQX				11036	//服务项目取消
#define	   FUNC_KH_QTYWSF				11037	//前台业务收费
#define	   FUNC_KH_CXQTYWSFBZ			11038	//查询前台业务收费标准


//资金交易类
#define	   FUNC_ZJ_ZJCQ			12001	//资金存取
#define	   FUNC_ZJ_HCLB			12003	//红冲兰补
#define	   FUNC_ZJ_YYCQ			12037	//存取预约
#define	   FUNC_ZJ_CXYYCQ_KH	12042	//查询客户预约存取明细
#define	   FUNC_ZJ_JYSJDJ		12050	//交易时间登记


//银证业务类

#define	   FUNC_YZZZ_CXYHYE		12506	//查询银行余额
#define	   FUNC_YZZZ_ZQ_ZZSQ	12507	//证券转帐申请
#define	   FUNC_YZZZ_KH_ZQZDLS   12531   //客户证券主动流水查询
#define	   FUNC_YZZZ_CXYZZZDY			12549	//查询银证转账对应关系
#define	   FUNC_YZZZ_CXDRZQLS			12551	//查询当日证券主动流水

//证券交易类
#define	   FUNC_JY_ZJMMJY		13001	//资金密码效验
#define	   FUNC_JY_JYMMJY		13002	//交易密码效验
#define	   FUNC_JY_MMWT			13003	//买卖委托
#define	   FUNC_JY_MMCD			13005	//买卖撤单
#define	   FUNC_JY_KMSLJS		13007	//可买入数量计算
#define	   FUNC_JY_PLMRWT		13014	//批量买入委托
#define	   FUNC_JY_PLMCWT		13015	//批量卖出委托

//交易查询类
#define	   FUNC_JY_DRWTCX		14001	//客户当日委托查询
#define	   FUNC_JY_DRCJCX		14002	//客户当日成交查询
#define	   FUNC_JY_FBCJCX		14003	//客户当日分笔成交查询
#define	   FUNC_JY_CCCX			14004	//客户持仓查询
#define	   FUNC_JY_LSWTCX		14005	//客户历史委托查询
#define	   FUNC_JY_LSCJCX		14006	//客户历史成交查询
#define	   FUNC_JY_HQCX			14028	//行情查询
#define	   FUNC_JY_KHPHCX		14032	//客户配号查询
#define	   FUNC_JY_CCHZCX		14010	//持仓汇总查询
#define	   FUNC_JY_KHZLCX		14011	//客户资料查询
#define	   FUNC_JY_GDHCX		14012	//客户股东号查询
#define	   FUNC_JY_ZJCX_ZJZH	14013	//资金查询按资金号
#define	   FUNC_JY_YHZHCX		14014	//客户银行帐号查询
#define	   FUNC_JY_ZJCX_KHH		14015	//资金查询按客户号
#define	   FUNC_JY_KHZJMXCX		14057	//客户资金明细查询
#define	   FUNC_JY_KHDRZJMXCX	14201	//客户当日资金明细查询
#define	   FUNC_JY_PZHCXZJMX	14062	//按凭证号查询资金明细

//投资理财类
#define	   FUNC_TZLC_LCZHCX		14501	//理财专户查询
#define	   FUNC_TZLC_DTHZZHDJ	14512	//动态合作帐户开户登记
#define	   FUNC_XT_GETSJZD		15006	//获得数据字典

//--------------------------------------------基金功能码定义----------------------------------------------

//投资人交易委托类
#define	   FUNC_JJ_JY_MMWT			19031   //基金买卖委托
#define	   FUNC_JJ_JY_WTCD			19032	//基金委托撤单
#define	   FUNC_JJ_JY_YYMMWT		19033	//基金预约买卖委托
//基金特殊交易类
#define	   FUNC_JJ_TSJY_JJZH		19043	//基金转换
#define	   FUNC_JJ_TSJY_SZFHFS		19045	//设置分红方式
#define	   FUNC_JJ_TSJY_DSDESGSZ	19046	//定时定额申购设置
#define	   FUNC_JJ_TSJY_DSDESGQX	19047	//定时定额申购取消
//交易对帐单打印类 
#define	  FUNC_JJ_DY_CJDZD			19051	//基金成交对帐单
#define	  FUNC_JJ_DY_ZJDZD			19052	//基金交易资金对帐单
//单户查询 
#define	  FUNC_JJ_CX_JJZH			19062	//单户基金帐户查询
#define	  FUNC_JJ_CX_JJZHFE			19063	//单户基金份额查询
#define	  FUNC_JJ_CX_JJWT			19065	//客户当日委托查询
#define	  FUNC_JJ_CX_JJZHWT			19066	//客户当日账户委托查询
#define	  FUNC_JJ_CX_JJFEBD			19067	//客户当日基金流水查询
#define	  FUNC_JJ_CX_FEDJJD			19068	//客户当日基金冻结解冻查询
#define	  FUNC_JJ_CX_JJWJS			19069	//客户基金未交收查询
#define	  FUNC_JJ_CX_JSZH			19070	//客户结算帐户查询
//参数类
#define	  FUNC_JJ_CS_CXYWDM			19081	//业务代码	
#define	  FUNC_JJ_CS_CXJSJG			19082	//基金外部结算机构
#define	  FUNC_JJ_CS_CXTAXX			19083	//基金公司信息
#define	  FUNC_JJ_CS_CXJJXX			19084	//基金信息
#define	  FUNC_JJ_CS_CXXSDZ			19085	//基金销售对照
#define	  FUNC_JJ_CS_CXDQDESGPZ		19086	//查询定期定额申购品种

//历史资料
#define	  FUNC_JJ_QTCX_JJCJ			19264	//全体基金成交查询
#define	  FUNC_JJ_CX_WTQRLS			19269	//基金委托确认流水查询
#define	  FUNC_JJ_CX_JJFHMX			19271	//基金分红明细查询 
#define	  FUNC_JJ_CX_WBZJQS			19272	//外部资金清算查询



//---------------------------------- 其它－－－－－－－－－－－－－－－－－－

#define	   FUNC_RPT_XMLFORMAT	1801	//查询报表样板
#define	   FUNC_RPT_TEST		1802	//测试报表
#define	   FUNC_XT_SQL			1803	//语句执行



#endif



